### ISSUE TITLE
Firefox not showing charaters

### ISSUE THREAD

**Issue by cannotparse** [tholman/unicoder.js#2]
![issue](https://cloud.githubusercontent.com/assets/5499093/6436198/78c87f74-c079-11e4-8766-bc7b7734b582.png)

I'm running Firefox 35.0.1 ("Mozilla Firefox for Linux Mint mint 1.0")

**Comment by cannotparse** [comment]
Also not working on google chrome for linux (Ubuntu [On mint 17.1]) version 40.0.2214.111

![issue2](https://cloud.githubusercontent.com/assets/5499093/6436251/47dbfff2-c07a-11e4-9095-fb9896928fe7.png)

**Comment by tholman** [comment]
I think I'm going to put this down as your computers not having the unicode fonts anywhere onboard. Do they display on chromium, on ubuntu/mint?

**Comment by mikeingz** [comment]
Works for me with Firefox 36.0.1 (Windows 8) but not with Chrome 41 (it also shows some squares for most of the fonts)

**Comment by tholman** [comment]
Going to close this off. Its down to the os, having characters for the most part.
